const { productsModel } = require("../model/products")

const data = [
    { id: 1, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/81HK954c4LL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/610Z0dk2N6S._SL1000_.jpg", productImage3: "https://m.media-amazon.com/images/I/51eKdJgi2pL._SL1040_.jpg", productTitle: "Acer Nitro Vg270 S 27 Inch (68.58 Cm) LCD 1920 x 1080 Pixels Monitor with LED Backlight Full Hd IPS Gaming I 0.5 Ms Response Time I 165Hz Refresh Rate I HDR 10 I AMD Radeon Free Sync I (Black)", productPrice: 13949, rating: 5 },
    { id: 2, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/71y-nJm3NiL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/91KMe39T03L._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/81Fvt12g-IL._SL1500_.jpg", productTitle: "HP 15s, 11th Gen Intel Core i5-1155G7, 15.6 inch(39.6cm) FHD Anti-Glare Laptop(8GB RAM/512 GB SSD/Intel Iris Xe Graphics/Win 11/Dual Speakers/Backlit KeyboardAlexa Built-in/MSO 2021) 15s-fr4000TU", productPrice: 52490, rating: 4.3 },
    { id: 3, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/71jG+e7roXL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/71-6roO29AL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/71z-1j187cL._SL1500_.jpg", productTitle: "Apple 2020 MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey", productPrice: 79990, rating: 4.1 },
    { id: 4, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/51cVJdMGznL._SL1000_.jpg", productImage2: "https://m.media-amazon.com/images/I/61NJJEoyHNL._SL1000_.jpg", productImage3: "https://m.media-amazon.com/images/I/51wQs0x5SzL._SL1000_.jpg", productTitle: "Lenovo IdeaPad Slim 3 Intel Core i3-1115G4 11th Gen 15.6(39.62cm) FHD Laptop(8GB/ 256GB SSD / Win 11 / Office 2021 / 2 Year Warranty / 3 Month Game Pass / Arctic Grey / 1.65Kg), 82H803GTIN", productPrice: 34990, rating: 3.7 },
    { id: 5, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/61S9aVnRZDL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/81DEzbJ9ERL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/71-SQ0I-HxL._SL1500_.jpg", productTitle: "Fire-Boltt Ninja Call Pro Plus 1.83 Smart Watch with Bluetooth Calling, AI Voice Assistance, 100 Sports Modes IP67 Rating, 240 * 280 Pixel High Resolution(Black) ", productPrice: 1499, rating: 4.3 },
    { id: 6, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/61SSVxTSs3L._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/61nAoz3GpRL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/619g-acf-GL._SL1500_.jpg", productTitle: "Noise Pulse 2 Max 1.85 Display, Bluetooth Calling Smart Watch, 10 Days Battery, 550 NITS Brightness, Smart DND, 100 Sports Modes, Smartwatch for Men and Women(Jet Black) ", productPrice: 1799, rating: 4.4 },
    { id: 7, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/61H5PEqBBAL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/61PbDF5yhZL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/71dC5JjtvDL._SL1500_.jpg", productTitle: "boAt Wave Call Smart Watch, Smart Talk with Advanced Dedicated Bluetooth Calling Chip, 1.69 HD Display with 550 NITS & 70% Color Gamut, 150+ Watch Faces, Multi-Sport Modes,HR,SpO2, IP68(Active Black)", productPrice: 1299, rating: 3.6 },
    { id: 8, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/41FUvKZGtvL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kHTZHNgyL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61x4lezCajL._SX679_.jpg", productTitle:"boAt Bassheads 162 in Ear Wired Earphones with Mic(Active Black)", productPrice: 300, rating: 4.2 },
    { id: 9, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/31IdiM9ZM8L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71E49jH4CbL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61ev3M9LmQL._SX679_.jpg", productTitle: "boAt BassHeads 100 in-Ear Wired Headphones with Mic (Black)", productPrice: 399, rating: 4.2 },
    { id: 10, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/31NnmYempPL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/91iPKswDKVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81n1wy0yAwL._SX679_.jpg", productTitle: "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button", productPrice: 590, rating: 3.1 },
    { id: 11, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/31DYx7AhW6L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61OKhA8evhL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/510VAFq6VWL._SX679_.jpg", productTitle: "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack", productPrice: 149, rating: 3.9 },
    { id: 12, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/4197+WUvDxL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61fZGx7vWFL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61zPX6+HXkL._SX679_.jpg", productTitle: "Amazon Basics USB Gaming Wired On-Ear Headphones with Detachable Mic, with Blue LED, Windows Software, Simulated 7.1 Surround Sound, 2.4 Meter Braided Cable Flexible Padded Ear Cushions(Black", productPrice: 1699, rating: 4.3 },
    { id: 13, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/81TUMM6wbGL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81RKFjo8tAL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/718iipdS3tL._UX679_.jpg", productTitle: "Fossil Machine Stainless Steel Chronograph Unisex Watch FS4682IE ", productPrice: 1499, rating: 4.2 },
    { id: 14, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/71u71acHDvS._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ev+opPE0L._UY679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51-ZPpT13FS._UX679_.jpg", productTitle: "Amazon Brand - Symbol Analog Men's Watch", productPrice: 1769, rating: 4.2 },
    { id: 15, category: "electronics", subCategory: "electronics", productImage1: "https://m.media-amazon.com/images/I/81HK954c4LL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/610Z0dk2N6S._SL1000_.jpg", productImage3: "https://m.media-amazon.com/images/I/51eKdJgi2pL._SL1040_.jpg", productTitle: "Acer Nitro Vg270 S 27 Inch (68.58 Cm) LCD 1920 x 1080 Pixels Monitor with LED Backlight Full Hd IPS Gaming I 0.5 Ms Response Time I 165Hz Refresh Rate I HDR 10 I AMD Radeon Free Sync I (Black)", productPrice: 13949, rating: 5 },
   
   
    { id: 16, category: "electronics", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41V4aNRci3L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6168dvBwOdL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613e9cMGbdL._SX679_.jpg", productTitle: "Samsung Galaxy S23 5G (Green, 8GB, 256GB Storage)", productPrice: 79999, rating: 4.9 },
    { id: 17, category: "electronics", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/91zMokvCNuL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81opNRY-92L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71qAb7BFZOL._SX679_.jpg", productTitle: "Samsung Galaxy M14 5G (Smoky Teal, 6GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery", productPrice: 15999, rating: 4.1 },
    { id: 18, category: "electronics", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/81t6Av5DvXL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/71pz7Jk3XuL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/51UC+Dnwr6L._SL1500_.jpg", productTitle: "Samsung Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus", productPrice: 7149, rating: 4.1 },
    { id: 19, category: "electronics", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/814ePfNubRL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/71jWIJ-I0wL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81AaDfJn5lL._SX679_.jpg", productTitle: "Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage", productPrice: 7119, rating: 4.7 },
    { id: 20, category: "electronics", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41CkKbseMGL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71R2u-n-bVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Vul6806pL._SX679_.jpg", productTitle: "Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM, 128GB Storage)", productPrice: 29999, rating: 4.4 },
    
    { id: 21, category: "electronics", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/811aBK9bUFL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61p6R+WqedL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51Kek7i7PkL._SX679_.jpg", productTitle: "HP Laptop 15s, Intel Celeron N4500, 15.6 inch(39.6cm) HD Laptop (8GB RAM,512GB SSD,Intel UHD Graphics,Dual Speakers,Numeric Keypad,Alexa,Win 11", productPrice: 28990, rating: 4.3 },
    { id: 22, category: "electronics", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41u9nT3v1sL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81KMXhii72L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GTckGbvkL._SX679_.jpg", productTitle: "HP Chromebook 15a Intel Celeron N4500 15.6 inch (39.6cm) HD,Anti-Glare, Micro-Edge Laptop(4GB RAM/128 GB eMMC/Intel UHD Graphics", productPrice: 17990, rating: 4.1 },
    { id: 23, category: "electronics", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41GiZW0OmLL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61D1-dFFkaL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/612Nc-slcRL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i5-1155G7, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB", productPrice: 54900, rating: 4.6 },
    { id: 24, category: "electronics", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41U2MBgAS0L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81pvQ2IKg5L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71wZH1BvQlL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i3-1115G4, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin & Light, Dual Speakers ", productPrice: 37830, rating: 4.2 },
    { id: 25, category: "electronics", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/419+q+HCwPL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71-yuf1JRHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/717XoM4zfeL._SX679_.jpg", productTitle: "HP Pavilion 15, AMD Ryzen 5 5625U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, AMD Radeon Graphics, FPR, Backlit KB, Audio by B&O, Thin & Light (Win 11, MSO 2021, Silver, 1.75 kg), eh2047AU", productPrice: 58990, rating: 4.9 },
   
    { id: 26, category: "electronics", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41TAKjYMgxL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71DINiJ0sVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61mi4jFkaVL._SX679_.jpg", productTitle: "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound, IPX7 Water Resistance, TWS Feature, Up to 12H Total Playtime, Multi-Compatibility Modes and Type-C Charging(Raging Black)", productPrice: 999, rating: 4.3 },
    { id: 27, category: "electronics", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41aZf9i-QzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61szskBdzNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81lkL-79AxL._SX679_.jpg", productTitle: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)", productPrice: 1599, rating: 4.2 },
    { id: 28, category: "electronics", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/51RTfgkScMS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61v6fH6YGrL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71N6u0TeZJL._SX679_.jpg", productTitle: "JBL Go 2, Wireless Portable Bluetooth Speaker with Mic, JBL Signature Sound, Vibrant Color Options with IPX7 Waterproof & AUX (Blue)", productPrice: 1775, rating: 4.3 },
    { id: 29, category: "electronics", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31iyxtzQDZL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/713B5ZJLKeL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61z7or3GmXL._SX679_.jpg", productTitle: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 40 Hours Play Time, Voice Assistance and Fast Charging (Blue)", productPrice: 999, rating: 4.2 },
    { id: 30, category: "electronics", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41peEHqkuNL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71hdbOLOIQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61jxrJXUWqL._SX679_.jpg", productTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Black)", productPrice: 1499, rating: 3.9 },
    
    { id: 31, category: "electronics", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/41-CKEKnjyL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6128yHfTihL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71PpaeMKW7L._SX679_.jpg", productTitle: "Fire-Boltt Phoenix Smart Watch with Bluetooth Calling 1.3 ,120+ Sports Modes, 240 * 240 PX High Res with SpO2, Heart Rate Monitoring & IP67 Rating (Silver Grey)", productPrice: 1399, rating: 3.9 },
    { id: 32, category: "electronics", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/41K+zyyjewL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/713UeEWZwTL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71bRx-oRY-L._SX679_.jpg", productTitle: "Fire-Boltt Newly Launched Ninja Call Pro Max 2.01” Display Smart Watch, Bluetooth Calling, 120+ Sports Modes, Health Suite, Voice Assistance (Pink)", productPrice: 1599, rating: 4.5 },
    { id: 33, category: "electronics", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/516cl1BtRVL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81C8rR+SXjL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71vHoL2MVCL._UX679_.jpg", productTitle: "DENZER HILLS Mens Big Face Stainless Steel Analog Quartz Watches Fashion Business Chronograph Wrist Watches for Men", productPrice: 425, rating: 4.7 },
    { id: 34, category: "electronics", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/81TUMM6wbGL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81RKFjo8tAL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/718iipdS3tL._UX679_.jpg", productTitle: "Fossil Machine Stainless Steel Chronograph Unisex Watch FS4682IE ", productPrice: 1499, rating: 4.2 },
    { id: 35, category: "electronics", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/71u71acHDvS._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ev+opPE0L._UY679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51-ZPpT13FS._UX679_.jpg", productTitle: "Amazon Brand - Symbol Analog Men's Watch", productPrice: 1769, rating: 4.2 },
   
    { id: 36, category: "electronics", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41uMj+WxiyL._SX300_SY300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51hIbn4ZyxS._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/41Y5hiLeQxS._SY879_.jpg", productTitle: "Samsung Galaxy Tab S7 FE 31.5 cm (12.4 inch) Large Display, S-Pen in Box, Slim Metal Body, Dolby Atmos Sound", productPrice: 41980, rating: 4.9 },
    { id: 37, category: "electronics", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41CF84t1CzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61B22fzv+cL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61Vw3Yv3syL._SX679_.jpg", productTitle: "Lenovo Tab P11 Plus Tablet (11 inch (27.94 cm), 6 GB, 128 GB, Wi-Fi+LTE, Voice Calling)", productPrice: 23999, rating: 4.2 },
    { id: 38, category: "electronics", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41IRaaVTflL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617ZXE-782L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GqJcnqOTL._SX679_.jpg", productTitle: "Lenovo Tab M10 5G |10.6 inch (26.9cm)| 6 GB, 128 GB Expandable|Wi-Fi+ 5G | 90 Hz, 2K Display", productPrice: 26999, rating: 3.9 },
    { id: 39, category: "electronics", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41Qi4q8cL+L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71m3q75paHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61O1hCsHkjL._SX679_.jpg", productTitle: "Lenovo Tab M10 FHD Plus (3rd Gen) (10.61 inch (26.94 cm), 6 GB, 128 GB, Wi-Fi), Storm Grey with Qualcomm Snapdragon Processor", productPrice: 18999, rating: 4.3 },
    { id: 40, category: "electronics", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41A0S1w+z6L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/615jhlbcvQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Whhrp4y1L._SX679_.jpg", productTitle: "Lenovo Tab M10 HD LED Tablet (10.1-inch, 2GB, 16GB, Cellular, WiFi Calling + WiFi, Volte Black)", productPrice: 7870, rating: 3.6 },
  
    
    { id: 41, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/71vNgTH3MzL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81xrTeZOCVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61S-whXLdsL._SX679_.jpg", productTitle: "Xiaomi 12 Pro | 5G (Noir Black, 8GB RAM, 256GB Storage) ", productPrice: 41000, rating: 4.1 },
    { id: 42, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41lUzcNHs3L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81VTKN5SORL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/41EzF4CKYbL._SX679_.jpg", productTitle: "Redmi Note 12 5G (Matte Black,8GB RAM, 256GB Storage)", productPrice: 20999, rating: 4.1 },
    { id: 43, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41Wd9J6nfpL._SY445_SX342_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61sz8FNBYLL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/815BMqSfq8L._SX679_.jpg", productTitle: "Redmi New 3 (Light Blue, 2GB RAM, 32GB Storage)", productPrice: 6499, rating: 4.5 },
    { id: 44, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41cMW15mZfL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71JAYI7N9mL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61dJKvsE1uL._SX679_.jpg", productTitle: "Mi 10i 5G (Pacific Sunrise, 8GB RAM, 128GB Storage) - 108MP Quad Camera | Snapdragon 750G Processor ", productPrice: 20449, rating: 4.8 },
    { id: 45, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41-T2ODZmDL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71NkVrR-WFL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/917of1vSOFL._SX679_.jpg", productTitle: "Redmi 12C (Mint Green, 4GB RAM, 64GB Storage) | High Performance ", productPrice: 7699, rating: 3.6 },
    { id: 46, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41V4aNRci3L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6168dvBwOdL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613e9cMGbdL._SX679_.jpg", productTitle: "Samsung Galaxy S23 5G (Green, 8GB, 256GB Storage)", productPrice: 79999, rating: 4.9 },
    { id: 47, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/91zMokvCNuL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81opNRY-92L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71qAb7BFZOL._SX679_.jpg", productTitle: "Samsung Galaxy M14 5G (Smoky Teal, 6GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery", productPrice: 15999, rating: 4.1 },
    { id: 48, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/81t6Av5DvXL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/71pz7Jk3XuL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/51UC+Dnwr6L._SL1500_.jpg", productTitle: "Samsung Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus", productPrice: 7149, rating: 4.1 },
    { id: 49, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/814ePfNubRL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/71jWIJ-I0wL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81AaDfJn5lL._SX679_.jpg", productTitle: "Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage", productPrice: 7119, rating: 4.7 },
    { id: 50, category: "mobile", subCategory: "mobile", productImage1: "https://m.media-amazon.com/images/I/41CkKbseMGL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71R2u-n-bVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Vul6806pL._SX679_.jpg", productTitle: "Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM, 128GB Storage)", productPrice: 29999, rating: 4.4 },
   
   
   
    { id: 51, category: "mobile", subCategory: "mi", productImage1: "https://m.media-amazon.com/images/I/71vNgTH3MzL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81xrTeZOCVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61S-whXLdsL._SX679_.jpg", productTitle: "Xiaomi 12 Pro | 5G (Noir Black, 8GB RAM, 256GB Storage) ", productPrice: 41000, rating: 4.1 },
    { id: 52, category: "mobile", subCategory: "mi", productImage1: "https://m.media-amazon.com/images/I/41lUzcNHs3L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81VTKN5SORL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/41EzF4CKYbL._SX679_.jpg", productTitle: "Redmi Note 12 5G (Matte Black,8GB RAM, 256GB Storage)", productPrice: 20999, rating: 4.1 },
    { id: 53, category: "mobile", subCategory: "mi", productImage1: "https://m.media-amazon.com/images/I/41Wd9J6nfpL._SY445_SX342_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61sz8FNBYLL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/815BMqSfq8L._SX679_.jpg", productTitle: "Redmi New 3 (Light Blue, 2GB RAM, 32GB Storage)", productPrice: 6499, rating: 4.5 },
    { id: 54, category: "mobile", subCategory: "mi", productImage1: "https://m.media-amazon.com/images/I/41cMW15mZfL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71JAYI7N9mL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61dJKvsE1uL._SX679_.jpg", productTitle: "Mi 10i 5G (Pacific Sunrise, 8GB RAM, 128GB Storage) - 108MP Quad Camera | Snapdragon 750G Processor ", productPrice: 20449, rating: 4.8 },
    { id: 55, category: "mobile", subCategory: "mi", productImage1: "https://m.media-amazon.com/images/I/41-T2ODZmDL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71NkVrR-WFL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/917of1vSOFL._SX679_.jpg", productTitle: "Redmi 12C (Mint Green, 4GB RAM, 64GB Storage) | High Performance ", productPrice: 7699, rating: 3.6 },
    
   
    { id: 56, category: "mobile", subCategory: "samsung", productImage1: "https://m.media-amazon.com/images/I/41V4aNRci3L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6168dvBwOdL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613e9cMGbdL._SX679_.jpg", productTitle: "Samsung Galaxy S23 5G (Green, 8GB, 256GB Storage)", productPrice: 79999, rating: 4.9 },
    { id: 57, category: "mobile", subCategory: "samsung", productImage1: "https://m.media-amazon.com/images/I/91zMokvCNuL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81opNRY-92L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71qAb7BFZOL._SX679_.jpg", productTitle: "Samsung Galaxy M14 5G (Smoky Teal, 6GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery", productPrice: 15999, rating: 4.1 },
    { id: 58, category: "mobile", subCategory: "samsung", productImage1: "https://m.media-amazon.com/images/I/81t6Av5DvXL._SL1500_.jpg", productImage2: "https://m.media-amazon.com/images/I/71pz7Jk3XuL._SL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/51UC+Dnwr6L._SL1500_.jpg", productTitle: "Samsung Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus", productPrice: 7149, rating: 4.1 },
    { id: 59, category: "mobile", subCategory: "samsung", productImage1: "https://m.media-amazon.com/images/I/814ePfNubRL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/71jWIJ-I0wL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81AaDfJn5lL._SX679_.jpg", productTitle: "Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage", productPrice: 7119, rating: 4.7 },
    { id: 60, category: "mobile", subCategory: "samsung", productImage1: "https://m.media-amazon.com/images/I/41CkKbseMGL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71R2u-n-bVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Vul6806pL._SX679_.jpg", productTitle: "Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM, 128GB Storage)", productPrice: 29999, rating: 4.4 },
   
   
   
    { id: 61, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/811aBK9bUFL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61p6R+WqedL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51Kek7i7PkL._SX679_.jpg", productTitle: "HP Laptop 15s, Intel Celeron N4500, 15.6 inch(39.6cm) HD Laptop (8GB RAM,512GB SSD,Intel UHD Graphics,Dual Speakers,Numeric Keypad,Alexa,Win 11", productPrice: 28990, rating: 4.3 },
    { id: 62, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41u9nT3v1sL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81KMXhii72L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GTckGbvkL._SX679_.jpg", productTitle: "HP Chromebook 15a Intel Celeron N4500 15.6 inch (39.6cm) HD,Anti-Glare, Micro-Edge Laptop(4GB RAM/128 GB eMMC/Intel UHD Graphics", productPrice: 17990, rating: 4.1 },
    { id: 63, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41GiZW0OmLL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61D1-dFFkaL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/612Nc-slcRL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i5-1155G7, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB", productPrice: 54900, rating: 4.6 },
    { id: 64, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41U2MBgAS0L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81pvQ2IKg5L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71wZH1BvQlL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i3-1115G4, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin & Light, Dual Speakers ", productPrice: 37830, rating: 4.2 },
    { id: 65, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/419+q+HCwPL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71-yuf1JRHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/717XoM4zfeL._SX679_.jpg", productTitle: "HP Pavilion 15, AMD Ryzen 5 5625U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, AMD Radeon Graphics, FPR, Backlit KB, Audio by B&O, Thin & Light (Win 11, MSO 2021, Silver, 1.75 kg), eh2047AU", productPrice: 58990, rating: 4.9 },
    { id: 66, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41W2DCM6fYL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71PPCuJeMwL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71G+zfVJzcL._SX679_.jpg", productTitle: "Dell 14 Laptop, Intel Core i3-1115G4/8GB/512GB/14.0 (35.56cm) FHD Display, TÜV Rheinland Certified Comfortview Reduce Harmful Blue Light Emissions", productPrice: 37490, rating: 3.9 },
    { id: 67, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41sENAvdjZL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61lNLXdbv9L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613w3EedgML._SX679_.jpg", productTitle: "Dell G15-5525 Gaming Laptop, R7-6800H, 16GB DDR5, 512GB SSD, AMD, NVIDIA RTX 3060 (6GB GDDR6), 15.6 (39.62Cms) FHD WVA AG, 165 Hz 300 nits, Win 11+ MSO'21, 15 Months McAfee, Phantom Grey", productPrice: 94999, rating: 4.8 },
    { id: 68, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/4185a2l6+UL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51fXijo8W5L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51dCzHYwj+L._SX679_.jpg", productTitle: "Dell Inspiron 5620 Laptop,I5-1240P,16Gb Ddr4,512Gb Ssd,Nvidia Geforce Mx570 (2Gb Gddr6),16 (40.64Cms) Fhd+ Wva Ag 250 Nits,Win 11+ Mso'21,Platinum Silver (Icc-C783531Win8,1.8Kgs),Intel", productPrice: 80990, rating: 4.1 },
    { id: 69, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/413AOjExflL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61VSv07kqoL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61RydGoW2VL._SX679_.jpg", productTitle: "Dell G15 5520 Gaming Laptop, Intel i5-12500H/16GB DDR5/1TB SSD/15.6 (39.62cm) FHD WVA AG 120Hz 250 nits/NVIDIA RTX 3050, 4 GB GDDR6/Win 11", productPrice: 75999, rating: 3.9 },
    { id: 70, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41-ZtZ5kpaL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61eZDZTuPYL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71x1S4F9ALL._SX679_.jpg", productTitle: "Dell 15 Laptop, Intel Core i5-1135G7/8GB/1TB+256GB SSD/15.6(39.62cm) FHD, Comfortview to Reduce Harmful Blue Light, Mobile Connect/Backlit KB + FPR/Win 11+MSO'21/15 Month McAfee/Black/1.69kg", productPrice: 50999, rating: 4.5 },
    { id: 71, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41eOBRPZX7L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kXM+SAG1S._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613xp-0qmAS._SX679_.jpg", productTitle: "Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 14 (35.56cm) FHD Thin & Light Laptop (8GB/512GB SSD/Windows 11/Office 2021/2Yr Warranty/3months Game Pass/Arctic Grey/1.41Kg), 82H701DNIN", productPrice: 38990, rating: 4.6 },
    { id: 72, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41o-KkXEkSL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61NJJEoyHNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51tncWCdtXL._SX679_.jpg", productTitle: "Lenovo IdeaPad Slim 3 Intel Core i3-1115G4 11th Gen 15.6(39.62cm) FHD Laptop (8GB/256GB SSD/Win 11/Office 2021/3 Month Game Pass/Arctic Grey/1.65Kg), 82H803TXIN", productPrice: 34990, rating: 3.9 },
    { id: 73, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/510pfCNfE+L._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/41U8CxRiglL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61w5xBxsBvL._SX679_.jpg", productTitle: "Lenovo ThinkPad E14 AMD Ryzen 5 7530U 14(35.56 cm) WUXGA IPS 300 Nits Thin and Light Laptop (16GB RAM/512GB SSD/Windows 11 Home/AMD Radeon Graphics/Backlit", productPrice: 58990, rating: 4.1 },
    { id: 74, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41D+zRXM2RL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61KqZczgmWL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51F2qguuw8L._SX679_.jpg", productTitle: "Lenovo V15 AMD Ryzen 5 5500U 15.6 (39.62cm) FHD 250 nits Antiglare Thin and Light Laptop (8GB/512GB SSD/Windows 11 Home/Iron Grey/1.7 Kg), 82KDA00XIH", productPrice: 34650, rating: 4.5 },
    { id: 75, category: "laptop", subCategory: "laptop", productImage1: "https://m.media-amazon.com/images/I/41bufC9IzpL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61WHe4UIk8L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61bcCd1CkCL._SX679_.jpg", productTitle: "Lenovo Ideapad Gaming 3 AMD Ryzen 5 5600H 15.6(39.62cm) FHD IPS Gaming Laptop (8GB/512GB SSD/4GB NVIDIA GTX 1650/120Hz/Win 11", productPrice: 55555, rating: 3.8 },
   
   
   
    { id: 76, category: "laptop", subCategory: "hp", productImage1: "https://m.media-amazon.com/images/I/811aBK9bUFL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61p6R+WqedL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51Kek7i7PkL._SX679_.jpg", productTitle: "HP Laptop 15s, Intel Celeron N4500, 15.6 inch(39.6cm) HD Laptop (8GB RAM,512GB SSD,Intel UHD Graphics,Dual Speakers,Numeric Keypad,Alexa,Win 11", productPrice: 28990, rating: 4.3 },
    { id: 77, category: "laptop", subCategory: "hp", productImage1: "https://m.media-amazon.com/images/I/41u9nT3v1sL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81KMXhii72L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GTckGbvkL._SX679_.jpg", productTitle: "HP Chromebook 15a Intel Celeron N4500 15.6 inch (39.6cm) HD,Anti-Glare, Micro-Edge Laptop(4GB RAM/128 GB eMMC/Intel UHD Graphics", productPrice: 17990, rating: 4.1 },
    { id: 78, category: "laptop", subCategory: "hp", productImage1: "https://m.media-amazon.com/images/I/41GiZW0OmLL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61D1-dFFkaL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/612Nc-slcRL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i5-1155G7, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB", productPrice: 54900, rating: 4.6 },
    { id: 79, category: "laptop", subCategory: "hp", productImage1: "https://m.media-amazon.com/images/I/41U2MBgAS0L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81pvQ2IKg5L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71wZH1BvQlL._SX679_.jpg", productTitle: "HP Laptop 15s, 11th Gen Intel Core i3-1115G4, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics, Thin & Light, Dual Speakers ", productPrice: 37830, rating: 4.2 },
    { id: 80, category: "laptop", subCategory: "hp", productImage1: "https://m.media-amazon.com/images/I/419+q+HCwPL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71-yuf1JRHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/717XoM4zfeL._SX679_.jpg", productTitle: "HP Pavilion 15, AMD Ryzen 5 5625U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, AMD Radeon Graphics, FPR, Backlit KB, Audio by B&O, Thin & Light (Win 11, MSO 2021, Silver, 1.75 kg), eh2047AU", productPrice: 58990, rating: 4.9 },
   
    { id: 81, category: "laptop", subCategory: "dell", productImage1: "https://m.media-amazon.com/images/I/41W2DCM6fYL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71PPCuJeMwL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71G+zfVJzcL._SX679_.jpg", productTitle: "Dell 14 Laptop, Intel Core i3-1115G4/8GB/512GB/14.0 (35.56cm) FHD Display, TÜV Rheinland Certified Comfortview Reduce Harmful Blue Light Emissions", productPrice: 37490, rating: 3.9 },
    { id: 82, category: "laptop", subCategory: "dell", productImage1: "https://m.media-amazon.com/images/I/41sENAvdjZL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61lNLXdbv9L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613w3EedgML._SX679_.jpg", productTitle: "Dell G15-5525 Gaming Laptop, R7-6800H, 16GB DDR5, 512GB SSD, AMD, NVIDIA RTX 3060 (6GB GDDR6), 15.6 (39.62Cms) FHD WVA AG, 165 Hz 300 nits, Win 11+ MSO'21, 15 Months McAfee, Phantom Grey", productPrice: 94999, rating: 4.8 },
    { id: 83, category: "laptop", subCategory: "dell", productImage1: "https://m.media-amazon.com/images/I/4185a2l6+UL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51fXijo8W5L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51dCzHYwj+L._SX679_.jpg", productTitle: "Dell Inspiron 5620 Laptop,I5-1240P,16Gb Ddr4,512Gb Ssd,Nvidia Geforce Mx570 (2Gb Gddr6),16 (40.64Cms) Fhd+ Wva Ag 250 Nits,Win 11+ Mso'21,Platinum Silver (Icc-C783531Win8,1.8Kgs),Intel", productPrice: 80990, rating: 4.1 },
    { id: 84, category: "laptop", subCategory: "dell", productImage1: "https://m.media-amazon.com/images/I/413AOjExflL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61VSv07kqoL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61RydGoW2VL._SX679_.jpg", productTitle: "Dell G15 5520 Gaming Laptop, Intel i5-12500H/16GB DDR5/1TB SSD/15.6 (39.62cm) FHD WVA AG 120Hz 250 nits/NVIDIA RTX 3050, 4 GB GDDR6/Win 11", productPrice: 75999, rating: 3.9 },
    { id: 85, category: "laptop", subCategory: "dell", productImage1: "https://m.media-amazon.com/images/I/41-ZtZ5kpaL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61eZDZTuPYL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71x1S4F9ALL._SX679_.jpg", productTitle: "Dell 15 Laptop, Intel Core i5-1135G7/8GB/1TB+256GB SSD/15.6(39.62cm) FHD, Comfortview to Reduce Harmful Blue Light, Mobile Connect/Backlit KB + FPR/Win 11+MSO'21/15 Month McAfee/Black/1.69kg", productPrice: 50999, rating: 4.5 },
    
    { id: 86, category: "laptop", subCategory: "lenovo", productImage1: "https://m.media-amazon.com/images/I/41eOBRPZX7L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kXM+SAG1S._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/613xp-0qmAS._SX679_.jpg", productTitle: "Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 14 (35.56cm) FHD Thin & Light Laptop (8GB/512GB SSD/Windows 11/Office 2021/2Yr Warranty/3months Game Pass/Arctic Grey/1.41Kg), 82H701DNIN", productPrice: 38990, rating: 4.6 },
    { id: 87, category: "laptop", subCategory: "lenovo", productImage1: "https://m.media-amazon.com/images/I/41o-KkXEkSL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61NJJEoyHNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51tncWCdtXL._SX679_.jpg", productTitle: "Lenovo IdeaPad Slim 3 Intel Core i3-1115G4 11th Gen 15.6(39.62cm) FHD Laptop (8GB/256GB SSD/Win 11/Office 2021/3 Month Game Pass/Arctic Grey/1.65Kg), 82H803TXIN", productPrice: 34990, rating: 3.9 },
    { id: 88, category: "laptop", subCategory: "lenovo", productImage1: "https://m.media-amazon.com/images/I/510pfCNfE+L._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/41U8CxRiglL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61w5xBxsBvL._SX679_.jpg", productTitle: "Lenovo ThinkPad E14 AMD Ryzen 5 7530U 14(35.56 cm) WUXGA IPS 300 Nits Thin and Light Laptop (16GB RAM/512GB SSD/Windows 11 Home/AMD Radeon Graphics/Backlit", productPrice: 58990, rating: 4.1 },
    { id: 89, category: "laptop", subCategory: "lenovo", productImage1: "https://m.media-amazon.com/images/I/41D+zRXM2RL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61KqZczgmWL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51F2qguuw8L._SX679_.jpg", productTitle: "Lenovo V15 AMD Ryzen 5 5500U 15.6 (39.62cm) FHD 250 nits Antiglare Thin and Light Laptop (8GB/512GB SSD/Windows 11 Home/Iron Grey/1.7 Kg), 82KDA00XIH", productPrice: 34650, rating: 4.5 },
    { id: 90, category: "laptop", subCategory: "lenovo", productImage1: "https://m.media-amazon.com/images/I/41bufC9IzpL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61WHe4UIk8L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61bcCd1CkCL._SX679_.jpg", productTitle: "Lenovo Ideapad Gaming 3 AMD Ryzen 5 5600H 15.6(39.62cm) FHD IPS Gaming Laptop (8GB/512GB SSD/4GB NVIDIA GTX 1650/120Hz/Win 11", productPrice: 55555, rating: 3.8 },
   
  
    { id: 91, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41FUvKZGtvL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kHTZHNgyL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61x4lezCajL._SX679_.jpg", productTitle:"boAt Bassheads 162 in Ear Wired Earphones with Mic(Active Black)", productPrice: 300, rating: 4.2 },
    { id: 92, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31IdiM9ZM8L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71E49jH4CbL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61ev3M9LmQL._SX679_.jpg", productTitle: "boAt BassHeads 100 in-Ear Wired Headphones with Mic (Black)", productPrice: 399, rating: 4.2 },
    { id: 93, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31NnmYempPL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/91iPKswDKVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81n1wy0yAwL._SX679_.jpg", productTitle: "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button", productPrice: 590, rating: 3.1 },
    { id: 94, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31DYx7AhW6L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61OKhA8evhL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/510VAFq6VWL._SX679_.jpg", productTitle: "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack", productPrice: 149, rating: 3.9 },
    { id: 95, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/4197+WUvDxL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61fZGx7vWFL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61zPX6+HXkL._SX679_.jpg", productTitle: "Amazon Basics USB Gaming Wired On-Ear Headphones with Detachable Mic, with Blue LED, Windows Software, Simulated 7.1 Surround Sound, 2.4 Meter Braided Cable Flexible Padded Ear Cushions(Black", productPrice: 1699, rating: 4.3 },
    { id: 96, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31KkyDTnjhL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61FJR3uaZOL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/617lJwA0qEL._SX679_.jpg", productTitle: "CrossBeats Groov Buds True Wireless in Ear Earbuds TWS, 55 Hours of Playtime, Quad mic ENC", productPrice: 1699, rating: 3.2 },
    { id: 97, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31iyxtzQDZL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/713B5ZJLKeL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61z7or3GmXL._SX679_.jpg", productTitle: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 40 Hours Play Time, Voice Assistance and Fast Charging (Blue)", productPrice: 999, rating: 4.2 },
    { id: 98, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/311qIs7vzfL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61CgA4Z9BgL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61IEsAROsPL._SX679_.jpg", productTitle: "Noise Buds VS104 Truly Wireless Earbuds with 45H of Playtime, Quad Mic with ENC, Instacharge(10 min=200 min), 13mm Driver,Low Latency, BT v5.2 (Mint Green)", productPrice: 1099, rating: 4.3 },
    { id: 99, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/51G8uAuohnL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/710508lJtUL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71dTF37zmxL._SX679_.jpg", productTitle: "boAt Immortal 141 TWS Gaming Earbuds with Enx Tech,Up to 40 Hrs Playtime,Signature Sound,Beast Mode,Ipx4 Resistance,Iwp Tech,RBG Lights,&USB Type-C Port(Black Sabre)", productPrice: 1000, rating: 4.1 },
    { id: 100, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/31Qmgo-iZiL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71H2Ygbtd-L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81NTsSj8gvL._SX679_.jpg", productTitle: "JBL Tune Beam Wireless ANC Earbuds (TWS) with Mic, Customized Extra Bass EQ, 48 Hrs Battery and Quick Charge, 4-Mics", productPrice: 6999, rating: 4.5 },
    { id: 101, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41TAKjYMgxL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71DINiJ0sVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61mi4jFkaVL._SX679_.jpg", productTitle: "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound, IPX7 Water Resistance, TWS Feature, Up to 12H Total Playtime, Multi-Compatibility Modes and Type-C Charging(Raging Black)", productPrice: 999, rating: 4.3 },
    { id: 102, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41aZf9i-QzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61szskBdzNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81lkL-79AxL._SX679_.jpg", productTitle: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)", productPrice: 1599, rating: 4.2 },
    { id: 103, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/51RTfgkScMS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61v6fH6YGrL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71N6u0TeZJL._SX679_.jpg", productTitle: "JBL Go 2, Wireless Portable Bluetooth Speaker with Mic, JBL Signature Sound, Vibrant Color Options with IPX7 Waterproof & AUX (Blue)", productPrice: 1775, rating: 4.3 },
    { id: 104, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41aZf9i-QzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61szskBdzNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81lkL-79AxL._SX679_.jpg", productTitle: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)", productPrice: 1599, rating: 4.2 },
    { id: 105, category: "headphones", subCategory: "headphones", productImage1: "https://m.media-amazon.com/images/I/41peEHqkuNL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71hdbOLOIQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61jxrJXUWqL._SX679_.jpg", productTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Black)", productPrice: 1499, rating: 3.9 },
   
   
    { id: 106, category: "headphones", subCategory: "wiredheadphone", productImage1: "https://m.media-amazon.com/images/I/41FUvKZGtvL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kHTZHNgyL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61x4lezCajL._SX679_.jpg", productTitle:"boAt Bassheads 162 in Ear Wired Earphones with Mic(Active Black)", productPrice: 300, rating: 4.2 },
    { id: 107, category: "headphones", subCategory: "wiredheadphone", productImage1: "https://m.media-amazon.com/images/I/31IdiM9ZM8L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71E49jH4CbL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61ev3M9LmQL._SX679_.jpg", productTitle: "boAt BassHeads 100 in-Ear Wired Headphones with Mic (Black)", productPrice: 399, rating: 4.2 },
    { id: 108, category: "headphones", subCategory: "wiredheadphone", productImage1: "https://m.media-amazon.com/images/I/31NnmYempPL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/91iPKswDKVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81n1wy0yAwL._SX679_.jpg", productTitle: "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button", productPrice: 590, rating: 3.1 },
    { id: 109, category: "headphones", subCategory: "wiredheadphone", productImage1: "https://m.media-amazon.com/images/I/31DYx7AhW6L._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61OKhA8evhL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/510VAFq6VWL._SX679_.jpg", productTitle: "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack", productPrice: 149, rating: 3.9 },
    { id: 110, category: "headphones", subCategory: "wiredheadphone", productImage1: "https://m.media-amazon.com/images/I/4197+WUvDxL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61fZGx7vWFL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61zPX6+HXkL._SX679_.jpg", productTitle: "Amazon Basics USB Gaming Wired On-Ear Headphones with Detachable Mic, with Blue LED, Windows Software, Simulated 7.1 Surround Sound, 2.4 Meter Braided Cable Flexible Padded Ear Cushions(Black", productPrice: 1699, rating: 4.3 },

    { id: 111, category: "headphones", subCategory: "earphones", productImage1: "https://m.media-amazon.com/images/I/31KkyDTnjhL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61FJR3uaZOL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/617lJwA0qEL._SX679_.jpg", productTitle: "CrossBeats Groov Buds True Wireless in Ear Earbuds TWS, 55 Hours of Playtime, Quad mic ENC", productPrice: 1699, rating: 3.2 },
    { id: 112, category: "headphones", subCategory: "earphones", productImage1: "https://m.media-amazon.com/images/I/31iyxtzQDZL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/713B5ZJLKeL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61z7or3GmXL._SX679_.jpg", productTitle: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 40 Hours Play Time, Voice Assistance and Fast Charging (Blue)", productPrice: 999, rating: 4.2 },
    { id: 113, category: "headphones", subCategory: "earphones", productImage1: "https://m.media-amazon.com/images/I/311qIs7vzfL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61CgA4Z9BgL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61IEsAROsPL._SX679_.jpg", productTitle: "Noise Buds VS104 Truly Wireless Earbuds with 45H of Playtime, Quad Mic with ENC, Instacharge(10 min=200 min), 13mm Driver,Low Latency, BT v5.2 (Mint Green)", productPrice: 1099, rating: 4.3 },
    { id: 114, category: "headphones", subCategory: "earphones", productImage1: "https://m.media-amazon.com/images/I/51G8uAuohnL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/710508lJtUL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71dTF37zmxL._SX679_.jpg", productTitle: "boAt Immortal 141 TWS Gaming Earbuds with Enx Tech,Up to 40 Hrs Playtime,Signature Sound,Beast Mode,Ipx4 Resistance,Iwp Tech,RBG Lights,&USB Type-C Port(Black Sabre)", productPrice: 1000, rating: 4.1 },
    { id: 115, category: "headphones", subCategory: "earphones", productImage1: "https://m.media-amazon.com/images/I/31Qmgo-iZiL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71H2Ygbtd-L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81NTsSj8gvL._SX679_.jpg", productTitle: "JBL Tune Beam Wireless ANC Earbuds (TWS) with Mic, Customized Extra Bass EQ, 48 Hrs Battery and Quick Charge, 4-Mics", productPrice: 6999, rating: 4.5 },
    
    { id: 116, category: "headphones", subCategory: "blutooth", productImage1: "https://m.media-amazon.com/images/I/41TAKjYMgxL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71DINiJ0sVL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61mi4jFkaVL._SX679_.jpg", productTitle: "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound, IPX7 Water Resistance, TWS Feature, Up to 12H Total Playtime, Multi-Compatibility Modes and Type-C Charging(Raging Black)", productPrice: 999, rating: 4.3 },
    { id: 117, category: "headphones", subCategory: "blutooth", productImage1: "https://m.media-amazon.com/images/I/41aZf9i-QzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61szskBdzNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81lkL-79AxL._SX679_.jpg", productTitle: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)", productPrice: 1599, rating: 4.2 },
    { id: 118, category: "headphones", subCategory: "blutooth", productImage1: "https://m.media-amazon.com/images/I/51RTfgkScMS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61v6fH6YGrL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71N6u0TeZJL._SX679_.jpg", productTitle: "JBL Go 2, Wireless Portable Bluetooth Speaker with Mic, JBL Signature Sound, Vibrant Color Options with IPX7 Waterproof & AUX (Blue)", productPrice: 1775, rating: 4.3 },
    { id: 119, category: "headphones", subCategory: "blutooth", productImage1: "https://m.media-amazon.com/images/I/41aZf9i-QzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61szskBdzNL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81lkL-79AxL._SX679_.jpg", productTitle: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)", productPrice: 1599, rating: 4.2 },
    { id: 120, category: "headphones", subCategory: "blutooth", productImage1: "https://m.media-amazon.com/images/I/41peEHqkuNL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71hdbOLOIQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61jxrJXUWqL._SX679_.jpg", productTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Black)", productPrice: 1499, rating: 3.9 },
   
   
   
    { id: 121, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/61uHEF2B1FL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61LaNrGh4qL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Hw4bVYQBL._SX679_.jpg", productTitle: "beatXP Marv Neo 1.85” (4.6 cm) Display, Bluetooth Calling Smart Watch, Smart AI Voice Assistant, 100+ Sports Modes, Heart & SpO2 Monitoring, IP68, Fast Charging (Iced Silver)", productPrice: 1099, rating: 4.3 },
    { id: 122, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/41+gKbBZl4L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/612gDhVLm-L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61CXJlrkY3L._SX679_.jpg", productTitle: "boAt Wave Style Smart Watch with 1.69 Square HD Display, DIY Watch Face Studio, Coins,HR & SpO2 Monitoring,7 Days Battery Life", productPrice: 1099, rating: 3.9 },
    { id: 123, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/419atiDFzvL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71gxwNQeduL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61NwW2EqQRL._SX679_.jpg", productTitle: "boAt Wave Leap Call Smart Watch with 1.83 HD Display, Advanced Bluetooth Calling, Coins,Multiple Watch Faces,Multi-Sports Modes, IP68, HR & SpO2, Metallic Design,Weather Forecasts(Cherry Blossom)", productPrice: 1499, rating: 4.5 },
    { id: 124, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/41-CKEKnjyL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6128yHfTihL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71PpaeMKW7L._SX679_.jpg", productTitle: "Fire-Boltt Phoenix Smart Watch with Bluetooth Calling 1.3 ,120+ Sports Modes, 240 * 240 PX High Res with SpO2, Heart Rate Monitoring & IP67 Rating (Silver Grey)", productPrice: 1399, rating: 3.9 },
    { id: 125, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/41K+zyyjewL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/713UeEWZwTL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71bRx-oRY-L._SX679_.jpg", productTitle: "Fire-Boltt Newly Launched Ninja Call Pro Max 2.01” Display Smart Watch, Bluetooth Calling, 120+ Sports Modes, Health Suite, Voice Assistance (Pink)", productPrice: 1599, rating: 4.5 },
    { id: 126, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/516cl1BtRVL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81C8rR+SXjL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71vHoL2MVCL._UX679_.jpg", productTitle: "DENZER HILLS Mens Big Face Stainless Steel Analog Quartz Watches Fashion Business Chronograph Wrist Watches for Men", productPrice: 425, rating: 4.7 },
    { id: 127, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/81TUMM6wbGL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81RKFjo8tAL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/718iipdS3tL._UX679_.jpg", productTitle: "Fossil Machine Stainless Steel Chronograph Unisex Watch FS4682IE ", productPrice: 1499, rating: 4.2 },
    { id: 128, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/71u71acHDvS._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ev+opPE0L._UY679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51-ZPpT13FS._UX679_.jpg", productTitle: "Amazon Brand - Symbol Analog Men's Watch", productPrice: 1769, rating: 4.2 },
    { id: 129, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/71GtycnHMtL._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/71+N6Wkd9nL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71KwUZsaYiL._UX679_.jpg", productTitle: "Matrix Day & Date Analog Men's Watch", productPrice: 500, rating: 4.1 },
    { id: 130, category: "watch", subCategory: "watch", productImage1: "https://m.media-amazon.com/images/I/61V5HLOJhTL._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ku-K77TuL._UL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/71tLxZYLb6L._UL1500_.jpg", productTitle: "Fastrack Analog Black Dial Unisex Watch-NG38003PP13W ", productPrice: 715, rating: 4.6 },
    
    { id: 131, category: "watch", subCategory: "smartwatch", productImage1: "https://m.media-amazon.com/images/I/61uHEF2B1FL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61LaNrGh4qL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Hw4bVYQBL._SX679_.jpg", productTitle: "beatXP Marv Neo 1.85” (4.6 cm) Display, Bluetooth Calling Smart Watch, Smart AI Voice Assistant, 100+ Sports Modes, Heart & SpO2 Monitoring, IP68, Fast Charging (Iced Silver)", productPrice: 1099, rating: 4.3 },
    { id: 132, category: "watch", subCategory: "smartwatch", productImage1: "https://m.media-amazon.com/images/I/41+gKbBZl4L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/612gDhVLm-L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61CXJlrkY3L._SX679_.jpg", productTitle: "boAt Wave Style Smart Watch with 1.69 Square HD Display, DIY Watch Face Studio, Coins,HR & SpO2 Monitoring,7 Days Battery Life", productPrice: 1099, rating: 3.9 },
    { id: 133, category: "watch", subCategory: "smartwatch", productImage1: "https://m.media-amazon.com/images/I/419atiDFzvL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71gxwNQeduL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61NwW2EqQRL._SX679_.jpg", productTitle: "boAt Wave Leap Call Smart Watch with 1.83 HD Display, Advanced Bluetooth Calling, Coins,Multiple Watch Faces,Multi-Sports Modes, IP68, HR & SpO2, Metallic Design,Weather Forecasts(Cherry Blossom)", productPrice: 1499, rating: 4.5 },
    { id: 134, category: "watch", subCategory: "smartwatch", productImage1: "https://m.media-amazon.com/images/I/41-CKEKnjyL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/6128yHfTihL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71PpaeMKW7L._SX679_.jpg", productTitle: "Fire-Boltt Phoenix Smart Watch with Bluetooth Calling 1.3 ,120+ Sports Modes, 240 * 240 PX High Res with SpO2, Heart Rate Monitoring & IP67 Rating (Silver Grey)", productPrice: 1399, rating: 3.9 },
    { id: 135, category: "watch", subCategory: "smartwatch", productImage1: "https://m.media-amazon.com/images/I/41K+zyyjewL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/713UeEWZwTL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71bRx-oRY-L._SX679_.jpg", productTitle: "Fire-Boltt Newly Launched Ninja Call Pro Max 2.01” Display Smart Watch, Bluetooth Calling, 120+ Sports Modes, Health Suite, Voice Assistance (Pink)", productPrice: 1599, rating: 4.5 },
   
    { id: 136, category: "watch", subCategory: "normalwatch", productImage1: "https://m.media-amazon.com/images/I/516cl1BtRVL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81C8rR+SXjL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71vHoL2MVCL._UX679_.jpg", productTitle: "DENZER HILLS Mens Big Face Stainless Steel Analog Quartz Watches Fashion Business Chronograph Wrist Watches for Men", productPrice: 425, rating: 4.7 },
    { id: 137, category: "watch", subCategory: "normalwatch", productImage1: "https://m.media-amazon.com/images/I/81TUMM6wbGL._UX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/81RKFjo8tAL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/718iipdS3tL._UX679_.jpg", productTitle: "Fossil Machine Stainless Steel Chronograph Unisex Watch FS4682IE ", productPrice: 1499, rating: 4.2 },
    { id: 138, category: "watch", subCategory: "normalwatch", productImage1: "https://m.media-amazon.com/images/I/71u71acHDvS._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ev+opPE0L._UY679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51-ZPpT13FS._UX679_.jpg", productTitle: "Amazon Brand - Symbol Analog Men's Watch", productPrice: 1769, rating: 4.2 },
    { id: 139, category: "watch", subCategory: "normalwatch", productImage1: "https://m.media-amazon.com/images/I/71GtycnHMtL._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/71+N6Wkd9nL._UX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71KwUZsaYiL._UX679_.jpg", productTitle: "Matrix Day & Date Analog Men's Watch", productPrice: 500, rating: 4.1 },
    { id: 140, category: "watch", subCategory: "normalwatch", productImage1: "https://m.media-amazon.com/images/I/61V5HLOJhTL._UY679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Ku-K77TuL._UL1500_.jpg", productImage3: "https://m.media-amazon.com/images/I/71tLxZYLb6L._UL1500_.jpg", productTitle: "Fastrack Analog Black Dial Unisex Watch-NG38003PP13W ", productPrice: 715, rating: 4.6 },
    
   
    { id: 141, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41SOyqWKhOL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81cY+TOCXgL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/815FdRN6xhL._SX679_.jpg", productTitle: "Samsung Galaxy Tab A8 26.69 cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Silver, (SM-X200NZSEINU)", productPrice: 16999, rating: 4.2 },
    { id: 142, category: "tab", subCategory: "tab", productImage1: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWWVv6kdcUXl2tAn3kRYx55EXShMZ9_3pSf7vc5ioX_x7MNFeyLTQjkYJD_1P0lVh6x2NbqOdxnNb3vKv9gccA5XsV0GqBqdlqDuTSTJpumrlO3zHqKns6uw", productImage2: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSum4LLKEuEmI-aOimUmCKuYbUgayD7K76sw2Zp9ZRaJWrAwSNatT31tMd2dEdGtJBOQ7DmHpsS3ldS7vRgDCWCDbDj7cpDlZqrWte1t5zXOdKMKcfUonNYHg", productImage3: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSBk2S38zjSkPxAlZSB-Fstk-tpKpkkmjJbSO_2YTqpBfi-2N4Masdpw_vSnoc1XRfcPmNiTEma_M1uMvIdfs2ht-rJI0_4tzD2PG7ouopCqzqNZHGDL5tp", productTitle: "realme Pad WiFi+4G Tablet | 4GB RAM 64GB", productPrice: 13000, rating: 4.1 },
    { id: 143, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/31ezJpaVVQL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81+Ivpw21aL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81QCuPs6IKL._SX679_.jpg", productTitle: "Samsung Galaxy Tab S8 | 27.81cm (11.0) LCD Display | 4nm Processor | 8,000 mAh Battery | Dolby Atmos Quad Speakers ", productPrice: 48000, rating: 4.6 },
    { id: 144, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/51ZQhSIZxQS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617W1AhO3gS._SL1100_.jpg", productImage3: "https://m.media-amazon.com/images/I/41snbM7g2XS._SL1500_.jpg", productTitle: "Samsung Galaxy Tab A7 Lite 8.7 inches with Calling, Slim Metal Body, Dolby Atmos Sound, RAM 3 GB, ROM 32 GB Expandable, Wi-Fi+4G Tablets, Gray", productPrice:12700, rating: 4.1 },
    { id: 145, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41uMj+WxiyL._SX300_SY300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51hIbn4ZyxS._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/41Y5hiLeQxS._SY879_.jpg", productTitle: "Samsung Galaxy Tab S7 FE 31.5 cm (12.4 inch) Large Display, S-Pen in Box, Slim Metal Body, Dolby Atmos Sound", productPrice: 41980, rating: 4.9 },
    { id: 146, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41CF84t1CzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61B22fzv+cL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61Vw3Yv3syL._SX679_.jpg", productTitle: "Lenovo Tab P11 Plus Tablet (11 inch (27.94 cm), 6 GB, 128 GB, Wi-Fi+LTE, Voice Calling)", productPrice: 23999, rating: 4.2 },
    { id: 147, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41IRaaVTflL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617ZXE-782L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GqJcnqOTL._SX679_.jpg", productTitle: "Lenovo Tab M10 5G |10.6 inch (26.9cm)| 6 GB, 128 GB Expandable|Wi-Fi+ 5G | 90 Hz, 2K Display", productPrice: 26999, rating: 3.9 },
    { id: 148, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41Qi4q8cL+L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71m3q75paHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61O1hCsHkjL._SX679_.jpg", productTitle: "Lenovo Tab M10 FHD Plus (3rd Gen) (10.61 inch (26.94 cm), 6 GB, 128 GB, Wi-Fi), Storm Grey with Qualcomm Snapdragon Processor", productPrice: 18999, rating: 4.3 },
    { id: 149, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41A0S1w+z6L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/615jhlbcvQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Whhrp4y1L._SX679_.jpg", productTitle: "Lenovo Tab M10 HD LED Tablet (10.1-inch, 2GB, 16GB, Cellular, WiFi Calling + WiFi, Volte Black)", productPrice: 7870, rating: 3.6 },
    { id: 150, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41Lf3e44akL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/41b4nz8EwfL.jpg", productImage3: "https://m.media-amazon.com/images/I/413tAIY76-L.jpg", productTitle: "Lenovo Calling Tab M8 2nd Gen Tablet (8-inch, 2GB, 32GB, Wi-Fi + 4G LTE + Calling), Iron Grey", productPrice: 8700, rating: 4.1 },
    { id: 151, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41TzH5xRkML._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/51wMVRxiDpL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/717-z0kLtML._SX679_.jpg", productTitle: "Xiaomi Pad 6| Qualcomm Snapdragon 870| 144Hz Refresh Rate| 8GB, 256GB", productPrice: 28000, rating: 4.3 },
    { id: 152, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/51DgLLc+LFL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61C+EvYlbrL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51iTpayufcL._SL1100_.jpg", productTitle: "Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Display ", productPrice: 15999, rating: 4.8 },
    { id: 153, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/31jUKdJdjHL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71XUKLLo-oL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Koxyd6ukL._SX679_.jpg", productTitle: "Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz Refresh Rate| 6GB, 128GB| 2.5K+ Display (10.95-inch/27.81cm)", productPrice: 25534, rating: 5 },
    { id: 154, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/51ezb9UgmmL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Eb9vtdSML._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61Oz5OmttEL._SX679_.jpg", productTitle:"MI Xiaomi Pad 5 Snapdragon 860, 2.5K Resolution, 120Hz Refresh Rate, DCI-P3, 27.81cm(10.95 inch) Dolby", productPrice: 30000, rating: 4.1 },
    { id: 155, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/51DgLLc+LFL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51tyDjRgMzL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61hItV-MMAL._SX679_.jpg", productTitle: "(Refurbished) Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Di", productPrice: 10000, rating: 4.2 },
    { id: 156, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/31lnKCQ7scL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/51O9e69rOiL._SL1080_.jpg", productImage3: "https://m.media-amazon.com/images/I/51B0-V7VPTL._SL1080_.jpg", productTitle: "realme Pad WiFi+4G Tablet  ", productPrice: 15000, rating: 3.9 },
    { id: 157, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41+MTrSD8IL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/718jxLgsUiL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81BqbkQJwpL._SX679_.jpg", productTitle: "realme Pad X WiFi Tablet | 4GB RAM 64GB", productPrice: 19000, rating: 4.5 },
    { id: 158, category: "tab", subCategory: "tab", productImage1: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWWVv6kdcUXl2tAn3kRYx55EXShMZ9_3pSf7vc5ioX_x7MNFeyLTQjkYJD_1P0lVh6x2NbqOdxnNb3vKv9gccA5XsV0GqBqdlqDuTSTJpumrlO3zHqKns6uw", productImage2: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSum4LLKEuEmI-aOimUmCKuYbUgayD7K76sw2Zp9ZRaJWrAwSNatT31tMd2dEdGtJBOQ7DmHpsS3ldS7vRgDCWCDbDj7cpDlZqrWte1t5zXOdKMKcfUonNYHg", productImage3: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSBk2S38zjSkPxAlZSB-Fstk-tpKpkkmjJbSO_2YTqpBfi-2N4Masdpw_vSnoc1XRfcPmNiTEma_M1uMvIdfs2ht-rJI0_4tzD2PG7ouopCqzqNZHGDL5tp", productTitle: "realme Pad WiFi+4G Tablet | 4GB RAM 64GB", productPrice: 13000, rating: 4.1 },
    { id: 159, category: "tab", subCategory: "tab", productImage1: "https://m.media-amazon.com/images/I/41+1tvJoAVL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kZoKjF99L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71gdzYffrJL._SX679_.jpg", productTitle: "realme Pad 2 8 GB RAM 256 GB ROM 11.5 inch with Wi-Fi+4G Tablet ", productPrice: 25500, rating: 4.4 },
    { id: 160, category: "tab", subCategory: "tab", productImage1: "https://i0.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-scaled.jpg?ssl=1&quality=80&w=800", productImage2: "https://i1.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-8-scaled.jpg?ssl=1&quality=80&w=728&h=546", productImage3: "https://i0.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-14-scaled.jpg?ssl=1&quality=80&w=728&h=546", productTitle: "Realme Pad", productPrice: 12000, rating: 3.5 },
   
    { id: 161, category: "tab", subCategory: "samsungtab", productImage1: "https://m.media-amazon.com/images/I/41SOyqWKhOL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81cY+TOCXgL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/815FdRN6xhL._SX679_.jpg", productTitle: "Samsung Galaxy Tab A8 26.69 cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Silver, (SM-X200NZSEINU)", productPrice: 16999, rating: 4.2 },
    { id: 162, category: "tab", subCategory: "samsungtab", productImage1: "https://m.media-amazon.com/images/I/51ZQhSIZxQS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617W1AhO3gS._SL1100_.jpg", productImage3: "https://m.media-amazon.com/images/I/41snbM7g2XS._SL1500_.jpg", productTitle: "Samsung Galaxy Tab A7 Lite 8.7 inches with Calling, Slim Metal Body, Dolby Atmos Sound, RAM 3 GB, ROM 32 GB Expandable, Wi-Fi+4G Tablets, Gray", productPrice:12700, rating: 4.1 },
    { id: 163, category: "tab", subCategory: "samsungtab", productImage1: "https://m.media-amazon.com/images/I/31ezJpaVVQL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/81+Ivpw21aL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81QCuPs6IKL._SX679_.jpg", productTitle: "Samsung Galaxy Tab S8 | 27.81cm (11.0) LCD Display | 4nm Processor | 8,000 mAh Battery | Dolby Atmos Quad Speakers ", productPrice: 48000, rating: 4.6 },
    { id: 164, category: "tab", subCategory: "samsungtab", productImage1: "https://m.media-amazon.com/images/I/51ZQhSIZxQS._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617W1AhO3gS._SL1100_.jpg", productImage3: "https://m.media-amazon.com/images/I/41snbM7g2XS._SL1500_.jpg", productTitle: "Samsung Galaxy Tab A7 Lite 8.7 inches with Calling, Slim Metal Body, Dolby Atmos Sound, RAM 3 GB, ROM 32 GB Expandable, Wi-Fi+4G Tablets, Gray", productPrice:12700, rating: 4.1 },
    { id: 165, category: "tab", subCategory: "samsungtab", productImage1: "https://m.media-amazon.com/images/I/41uMj+WxiyL._SX300_SY300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51hIbn4ZyxS._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/41Y5hiLeQxS._SY879_.jpg", productTitle: "Samsung Galaxy Tab S7 FE 31.5 cm (12.4 inch) Large Display, S-Pen in Box, Slim Metal Body, Dolby Atmos Sound", productPrice: 41980, rating: 4.9 },
   
    { id: 166, category: "tab", subCategory: "lenovotab", productImage1: "https://m.media-amazon.com/images/I/41CF84t1CzL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/61B22fzv+cL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61Vw3Yv3syL._SX679_.jpg", productTitle: "Lenovo Tab P11 Plus Tablet (11 inch (27.94 cm), 6 GB, 128 GB, Wi-Fi+LTE, Voice Calling)", productPrice: 23999, rating: 4.2 },
    { id: 167, category: "tab", subCategory: "lenovotab", productImage1: "https://m.media-amazon.com/images/I/41IRaaVTflL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/617ZXE-782L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61GqJcnqOTL._SX679_.jpg", productTitle: "Lenovo Tab M10 5G |10.6 inch (26.9cm)| 6 GB, 128 GB Expandable|Wi-Fi+ 5G | 90 Hz, 2K Display", productPrice: 26999, rating: 3.9 },
    { id: 168, category: "tab", subCategory: "lenovotab", productImage1: "https://m.media-amazon.com/images/I/41Qi4q8cL+L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/71m3q75paHL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61O1hCsHkjL._SX679_.jpg", productTitle: "Lenovo Tab M10 FHD Plus (3rd Gen) (10.61 inch (26.94 cm), 6 GB, 128 GB, Wi-Fi), Storm Grey with Qualcomm Snapdragon Processor", productPrice: 18999, rating: 4.3 },
    { id: 169, category: "tab", subCategory: "lenovotab", productImage1: "https://m.media-amazon.com/images/I/41A0S1w+z6L._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/615jhlbcvQL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Whhrp4y1L._SX679_.jpg", productTitle: "Lenovo Tab M10 HD LED Tablet (10.1-inch, 2GB, 16GB, Cellular, WiFi Calling + WiFi, Volte Black)", productPrice: 7870, rating: 3.6 },
    { id: 170, category: "tab", subCategory: "lenovotab", productImage1: "https://m.media-amazon.com/images/I/41Lf3e44akL._SY300_SX300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/41b4nz8EwfL.jpg", productImage3: "https://m.media-amazon.com/images/I/413tAIY76-L.jpg", productTitle: "Lenovo Calling Tab M8 2nd Gen Tablet (8-inch, 2GB, 32GB, Wi-Fi + 4G LTE + Calling), Iron Grey", productPrice: 8700, rating: 4.1 },
   
    { id: 171, category: "tab", subCategory: "xiaomitab", productImage1: "https://m.media-amazon.com/images/I/41TzH5xRkML._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/51wMVRxiDpL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/717-z0kLtML._SX679_.jpg", productTitle: "Xiaomi Pad 6| Qualcomm Snapdragon 870| 144Hz Refresh Rate| 8GB, 256GB", productPrice: 28000, rating: 4.3 },
    { id: 172, category: "tab", subCategory: "xiaomitab", productImage1: "https://m.media-amazon.com/images/I/51DgLLc+LFL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61C+EvYlbrL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/51iTpayufcL._SL1100_.jpg", productTitle: "Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Display ", productPrice: 15999, rating: 4.8 },
    { id: 173, category: "tab", subCategory: "xiaomitab", productImage1: "https://m.media-amazon.com/images/I/31jUKdJdjHL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/71XUKLLo-oL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71Koxyd6ukL._SX679_.jpg", productTitle: "Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz Refresh Rate| 6GB, 128GB| 2.5K+ Display (10.95-inch/27.81cm)", productPrice: 25534, rating: 5 },
    { id: 174, category: "tab", subCategory: "xiaomitab", productImage1: "https://m.media-amazon.com/images/I/51ezb9UgmmL._SX679_.jpg", productImage2: "https://m.media-amazon.com/images/I/61Eb9vtdSML._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61Oz5OmttEL._SX679_.jpg", productTitle:"MI Xiaomi Pad 5 Snapdragon 860, 2.5K Resolution, 120Hz Refresh Rate, DCI-P3, 27.81cm(10.95 inch) Dolby", productPrice: 30000, rating: 4.1 },
    { id: 175, category: "tab", subCategory: "xiaomitab", productImage1: "https://m.media-amazon.com/images/I/51DgLLc+LFL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/51tyDjRgMzL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/61hItV-MMAL._SX679_.jpg", productTitle: "(Refurbished) Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Di", productPrice: 10000, rating: 4.2 },
   
    { id: 176, category: "tab", subCategory: "realmetab", productImage1: "https://m.media-amazon.com/images/I/31lnKCQ7scL._SX300_SY300_QL70_FMwebp_.jpg", productImage2: "https://m.media-amazon.com/images/I/51O9e69rOiL._SL1080_.jpg", productImage3: "https://m.media-amazon.com/images/I/51B0-V7VPTL._SL1080_.jpg", productTitle: "realme Pad WiFi+4G Tablet  ", productPrice: 15000, rating: 3.9 },
    { id: 177, category: "tab", subCategory: "realmetab", productImage1: "https://m.media-amazon.com/images/I/41+MTrSD8IL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/718jxLgsUiL._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/81BqbkQJwpL._SX679_.jpg", productTitle: "realme Pad X WiFi Tablet | 4GB RAM 64GB", productPrice: 19000, rating: 4.5 },
    { id: 178, category: "tab", subCategory: "realmetab", productImage1: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWWVv6kdcUXl2tAn3kRYx55EXShMZ9_3pSf7vc5ioX_x7MNFeyLTQjkYJD_1P0lVh6x2NbqOdxnNb3vKv9gccA5XsV0GqBqdlqDuTSTJpumrlO3zHqKns6uw", productImage2: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSum4LLKEuEmI-aOimUmCKuYbUgayD7K76sw2Zp9ZRaJWrAwSNatT31tMd2dEdGtJBOQ7DmHpsS3ldS7vRgDCWCDbDj7cpDlZqrWte1t5zXOdKMKcfUonNYHg", productImage3: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSBk2S38zjSkPxAlZSB-Fstk-tpKpkkmjJbSO_2YTqpBfi-2N4Masdpw_vSnoc1XRfcPmNiTEma_M1uMvIdfs2ht-rJI0_4tzD2PG7ouopCqzqNZHGDL5tp", productTitle: "realme Pad WiFi+4G Tablet | 4GB RAM 64GB", productPrice: 13000, rating: 4.1 },
    { id: 179, category: "tab", subCategory: "realmetab", productImage1: "https://i0.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-scaled.jpg?ssl=1&quality=80&w=800", productImage2: "https://i1.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-8-scaled.jpg?ssl=1&quality=80&w=728&h=546", productImage3: "https://i0.wp.com/www.smartprix.com/bytes/wp-content/uploads/2021/09/Realme-Pad-Review-14-scaled.jpg?ssl=1&quality=80&w=728&h=546", productTitle: "Realme Pad", productPrice: 12000, rating: 3.5 },
    { id: 180, category: "tab", subCategory: "realmetab", productImage1: "https://m.media-amazon.com/images/I/41+1tvJoAVL._SY300_SX300_.jpg", productImage2: "https://m.media-amazon.com/images/I/61kZoKjF99L._SX679_.jpg", productImage3: "https://m.media-amazon.com/images/I/71gdzYffrJL._SX679_.jpg", productTitle: "realme Pad 2 8 GB RAM 256 GB ROM 11.5 inch with Wi-Fi+4G Tablet ", productPrice: 25500, rating: 4.4 },
    
]

const addData = async (req, res) => {
    await productsModel.insertMany(data)
    res.send("Data added successfully")
}
const allData = async (req, res) => {
    const data = await productsModel.find()
    res.send(data)
}
const electronics = async (req, res) => {
    const data = await productsModel.find({ category: "electronics" })
    res.send(data)
}



const mobile= async (req, res) => {
    const data = await productsModel.find({ category: "mobile" })
    res.send(data)
}
const mi = async (req, res) => {
    const data = await productsModel.find({ subCategory: "mi" })
    res.send(data)
}
const samsung= async (req, res) => {
    const data = await productsModel.find({ subCategory: "samsung" })
    res.send(data)
}


const laptop = async (req, res) => {
    const data = await productsModel.find({ category: "laptop" })
    res.send(data)
}
const hp = async (req, res) => {
    const data = await productsModel.find({ subCategory: "hp" })
    res.send(data)
}
const dell = async (req, res) => {
    const data = await productsModel.find({ subCategory: "dell" })
    res.send(data)
}
const lenovo = async (req, res) => {
    const data = await productsModel.find({ subCategory: "lenovo" })
    res.send(data)
}



const headphones = async (req, res) => {
    const data = await productsModel.find({ category: "headphones" })
    res.send(data)
}
const wiredheadphone = async (req, res) => {
    const data = await productsModel.find({ subCategory: "wiredheadphone" })
    res.send(data)
}
const earphones = async (req, res) => {
    const data = await productsModel.find({ subCategory: "earphones" })
    res.send(data)
}
const blutooth = async (req, res) => {
    const data = await productsModel.find({ subCategory: "blutooth" })
    res.send(data)
}


const watch = async (req, res) => {
    const data = await productsModel.find({ category: "watch" })
    res.send(data)
}
const smartwatch= async (req, res) => {
    const data = await productsModel.find({ subCategory: "smartwatch" })
    res.send(data)
}
const normalwatch = async (req, res) => {
    const data = await productsModel.find({ subCategory: "normalwatch" })
    res.send(data)
}



const tab = async (req, res) => {
    const data = await productsModel.find({ category: "tab" })
    res.send(data)
}
const samsungtab = async (req, res) => {
    const data = await productsModel.find({ subCategory: "samsungtab" })
    res.send(data)
}
const lenovotab= async (req, res) => {
    const data = await productsModel.find({ subCategory: "lenovetab" })
    res.send(data)
}
const xiaomitab = async (req, res) => {
    const data = await productsModel.find({ subCategory: "xiaomitab" })
    res.send(data)
}
const realmetab = async (req, res) => {
    const data = await productsModel.find({ subCategory: "realmetab" })
    res.send(data)
}

module.exports = { addData, allData, electronics,
     mobile, mi, samsung,
     laptop, hp, dell, lenovo,
     headphones, wiredheadphone, earphones, blutooth, 
    watch, smartwatch, normalwatch, 
    tab, samsungtab, lenovotab, xiaomitab, realmetab }